# Generated by Django 3.2.3 on 2022-05-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.AutoField(default=-1, primary_key=True, serialize=False, unique=True)),
                ('IDSensor', models.TextField()),
                ('Fecha', models.DateField()),
                ('Hora', models.DurationField()),
                ('Temperatura', models.TextField()),
                ('Humedad', models.TextField()),
            ],
        ),
    ]
